#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: ./scripts/configure_codex_client.sh

Interactive by default. For non-interactive use, set:
  NEWAPI_BASE_URL
  NEWAPI_API_KEY
Optional:
  CODEX_MODEL             (default: deepseek-v4-flash-0731-target)
  CODEX_CONTEXT_WINDOW    (default: 262144)
  DSV4_CLIENT_HOME        (test/alternate home; default: current user's HOME)
EOF
}

case "${1:-}" in
  -h|--help)
    usage
    exit 0
    ;;
  "") ;;
  *)
    usage >&2
    exit 2
    ;;
esac

client_home=${DSV4_CLIENT_HOME:-${HOME:?HOME is required}}
base_url=${NEWAPI_BASE_URL:-}
api_key=${NEWAPI_API_KEY:-}
model_name=${CODEX_MODEL:-deepseek-v4-flash-0731-target}
context_window=${CODEX_CONTEXT_WINDOW:-262144}

if [[ -z "$base_url" && -t 0 ]]; then
  read -r -p 'New API address (for example https://newapi.example.com): ' base_url
fi
if [[ -z "$api_key" && -t 0 ]]; then
  read -r -s -p 'New API Token (input hidden): ' api_key
  printf '\n'
fi
if [[ -t 0 ]]; then
  read -r -p "Model name [$model_name]: " entered_model
  model_name=${entered_model:-$model_name}
  read -r -p "Context window [$context_window]: " entered_context
  context_window=${entered_context:-$context_window}
fi

[[ -n "$base_url" ]] || {
  printf 'NEWAPI_BASE_URL is required\n' >&2
  exit 2
}
[[ -n "$api_key" ]] || {
  printf 'NEWAPI_API_KEY is required\n' >&2
  exit 2
}
[[ -n "$model_name" ]] || {
  printf 'CODEX_MODEL must not be empty\n' >&2
  exit 2
}
[[ "$context_window" =~ ^[1-9][0-9]*$ ]] || {
  printf 'CODEX_CONTEXT_WINDOW must be a positive integer: %s\n' "$context_window" >&2
  exit 2
}
[[ "$base_url" == http://* || "$base_url" == https://* ]] || {
  printf 'NEWAPI_BASE_URL must start with http:// or https://\n' >&2
  exit 2
}

for value_name in base_url model_name; do
  value=${!value_name}
  if [[ "$value" == *$'\n'* || "$value" == *'"'* || "$value" == *'\\'* ]]; then
    printf '%s contains a character that is unsafe in generated TOML\n' "$value_name" >&2
    exit 2
  fi
done

base_url=${base_url%/}
if [[ "$base_url" != */v1 ]]; then
  base_url="$base_url/v1"
fi

codex_dir=${CODEX_HOME:-"$client_home/.codex"}
secret_dir="$client_home/.config/dsv4-codex"
launcher_dir="$client_home/.local/bin"
profile_file="$codex_dir/dsv4.config.toml"
key_file="$secret_dir/api-key"
launcher_file="$launcher_dir/codex-dsv4"
timestamp=$(date -u +%Y%m%dT%H%M%SZ)

umask 077
mkdir -p "$codex_dir" "$secret_dir" "$launcher_dir"

if [[ -e "$profile_file" ]]; then
  cp -a "$profile_file" "$profile_file.before-$timestamp"
  printf 'Backed up existing profile: %s\n' "$profile_file.before-$timestamp"
fi

cat >"$profile_file" <<EOF
# Generated by DeepSeek V4 A100 offline bundle.
model = "$model_name"
model_provider = "dsv4_newapi"
model_context_window = $context_window

[model_providers.dsv4_newapi]
name = "DeepSeek V4 Flash 0731 via New API"
base_url = "$base_url"
env_key = "DSV4_NEWAPI_KEY"
wire_api = "responses"
request_max_retries = 4
stream_max_retries = 5
stream_idle_timeout_ms = 300000
EOF
chmod 600 "$profile_file"

printf '%s' "$api_key" >"$key_file"
chmod 600 "$key_file"

cat >"$launcher_file" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

key_file=${DSV4_CODEX_KEY_FILE:-"${HOME:?HOME is required}/.config/dsv4-codex/api-key"}
[[ -r "$key_file" ]] || {
  printf 'Codex API key file is not readable: %s\n' "$key_file" >&2
  exit 1
}
export DSV4_NEWAPI_KEY
DSV4_NEWAPI_KEY=$(<"$key_file")
[[ -n "$DSV4_NEWAPI_KEY" ]] || {
  printf 'Codex API key file is empty: %s\n' "$key_file" >&2
  exit 1
}
exec codex --profile dsv4 "$@"
EOF
chmod 700 "$launcher_file"

printf '\nCODEX_CLIENT_CONFIGURED=YES\n'
printf 'PROFILE=%s\n' "$profile_file"
printf 'KEY_FILE=%s (mode 0600)\n' "$key_file"
printf 'LAUNCHER=%s\n' "$launcher_file"
if command -v codex >/dev/null 2>&1; then
  codex --version || true
else
  printf 'WARNING: codex is not currently in PATH; configuration was still created.\n' >&2
fi
printf '\nStart with:\n  %s\n' "$launcher_file"
